# Generated by Django 4.2.4 on 2024-04-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_destination', models.CharField(choices=[('GIKI', 'GIKI'), ('Peshawar', 'Peshawar'), ('Abbotabad', 'Abbotabad'), ('Pindi', 'Pindi'), ('Islamabad', 'Islamabad')], max_length=20)),
                ('to_destination', models.CharField(choices=[('GIKI', 'GIKI'), ('Peshawar', 'Peshawar'), ('Abbotabad', 'Abbotabad'), ('Pindi', 'Pindi'), ('Islamabad', 'Islamabad')], max_length=20)),
                ('bus_No', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('bus_location', models.CharField(max_length=100)),
            ],
        ),
    ]
